const USER_AGENT_MAX_LENGTH: usize = 512;
const PAGE_NAME_MAX_LENGTH: usize = 256;
const EVENT_NAME_MAX_LENGTH: usize = 256;
const REFERRER_MAX_LENGTH: usize = 512;
const EVENT_PROPERTY_MAX_LENGTH: usize = 1024;
const EVENT_PROPERTIES_MAX_SIZE: usize = 20000; // 20KB
const EVENT_URLMAX_LENGTH: usize = 2048;
const EVENT_USER_ID_MAX_LENGTH: usize = 256;
