pub const USER_AGENT_MAX_LENGTH: usize = 512;
pub const PAGE_NAME_MAX_LENGTH: usize = 256;
pub const EVENT_NAME_MAX_LENGTH: usize = 256;
pub const REFERRER_MAX_LENGTH: usize = 512;
pub const EVENT_PROPERTY_MAX_LENGTH: usize = 1024;
pub const EVENT_PROPERTIES_MAX_SIZE: usize = 20000; // 20KB
pub const EVENT_URL_MAX_LENGTH: usize = 2048;
pub const EVENT_USER_ID_MAX_LENGTH: usize = 256;
pub const MAX_SCREEN_WIDTH: i64 = 20_000;
pub const MAX_SCREEN_HEIGHT: i64 = 20_000;
