ALTER TABLE inbox_chatbox_preferences
ADD COLUMN twitter_url TEXT NOT NULL DEFAULT '',
ADD COLUMN facebook_url TEXT NOT NULL DEFAULT '',
ADD COLUMN public_email TEXT NOT NULL DEFAULT '',
ADD COLUMN instagram_url TEXT NOT NULL DEFAULT '',
ADD COLUMN whatsapp_number TEXT NOT NULL DEFAULT '',
ADD COLUMN mastodon_url TEXT NOT NULL DEFAULT '',
ADD COLUMN website_url TEXT NOT NULL DEFAULT '',
ADD COLUMN telegram_url TEXT NOT NULL DEFAULT '';

ALTER TABLE inbox_chatbox_preferences
ALTER COLUMN twitter_url DROP DEFAULT,
ALTER COLUMN facebook_url DROP DEFAULT,
ALTER COLUMN public_email DROP DEFAULT,
ALTER COLUMN instagram_url DROP DEFAULT,
ALTER COLUMN whatsapp_number DROP DEFAULT,
ALTER COLUMN mastodon_url DROP DEFAULT,
ALTER COLUMN website_url DROP DEFAULT,
ALTER COLUMN telegram_url DROP DEFAULT;
